name: Security Scan
on: [pull_request, push]
env:
  IMAGE_NAME: docker.io/library/check-it-out 
jobs:
  container-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build container
        run: |
          docker build -t $IMAGE_NAME:latest .          
      - name: Scan container
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker://${{ env.IMAGE_NAME }}:latest"
          format: "json"
          exit-code: "1"
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true
          output: "trivy-results.json"
      - name: Print Results
        uses: ManoCorp/check-it-out@main
        with:
          app-name: trivy
          output-file: trivy-results.json

