name: Security Scan
on: [pull_request, push]

jobs:
  container-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build container
        run: |
          docker build -t $GITHUB_REPOSITORY:latest .          
      - name: Scan container
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "docker://$GITHUB_REPOSITORY:latest"
          format: "json"
          exit-code: "1"
          severity: "CRITICAL,HIGH"
          ignore-unfixed: true
          output: "trivy-results.json"
      - name: Print Results
        uses: ../../
        with:
          app-name: trivy
          output-file: trivy-results.json

